### ISSUE TITLE
Adds CORS headers to all responses, even if they are not CORS requests

### ISSUE THREAD

**Issue by JamesMGreene** [BigstickCarpet/swagger-express-middleware#41] opened 2016-03-16 16:01 UTC
When enabling the CORS middleware, it inappropriately adds CORS-related response headers for **ALL** requests &mdash; not _just_ for CORS requests.

e.g.

```
$ curl -ki https://localhost/api/v1/about

HTTP/1.1 200 OK
Date: Wed, 16 Mar 2016 15:42:32 GMT
Server: Apache
X-Powered-By: Express
access-control-allow-origin: *
access-control-allow-methods: GET, OPTIONS
access-control-allow-headers:
Access-Control-Allow-Credentials: false
access-control-max-age: 0
Content-Type: application/json; charset=utf-8
Content-Length: 44
ETag: W/"15e-ldRTnVwhpSAI2P0bgpa0Zw"
Vary: Accept-Encoding

{"version":{"major":1,"minor":0,"patch":0}}
```

Per the [CORS spec's "Resource Processing Model" section](https://www.w3.org/TR/cors/#resource-processing-model), requests without the `Origin` header present are _not_ CORS requests.

**Comment by BigstickCarpet** [comment] 2016-03-16 16:22
Closing this as a duplicate of #42

**Comment by JamesMGreene** [comment] 2016-03-16 16:25
It's not really a duplicate, IMHO, but I don't mind you closing it as long as both bug are dealt with.

The difference here is that this bug effects all HTTP methods, not just `OPTIONS` requests.

**Comment by BigstickCarpet** [comment] 2016-03-16 16:29
Ah, ok.  I didn't notice the subtle difference between the two issues.  Thanks for pointing that out.

However, as I read the spec, CORS headers should be added to _all_ requests for any cross-origin resource, not just `OPTIONS` requests.  As long as the `Origin` header is present, the headers should be set.  At least, that's the behavior I've seen in the wild, and it seems to comply with the spec.

**Comment by JamesMGreene** [comment] 2016-03-16 16:49
> However, as I read the spec, CORS headers should be added to all requests for any cross-origin resource, not just OPTIONS requests. As long as the Origin header is present, the headers should be set. At least, that's the behavior I've seen in the wild, and it seems to comply with the spec.

Yeah, that generally seems to be how it's done.

**Comment by BigstickCarpet** [comment] 2016-03-16 16:55
Ok. cool.  Then I'll leave that part of the CORS middleware as-is.  But, as you pointed out, it should _only_ set the headers if the `Origin` header is present.  I'll address that bug as part of #42

**Closed by BigstickCarpet** 2016-03-16 16:55 UTC

**Comment by JamesMGreene** [comment] 2016-03-16 16:59
:+1:
